### PR TITLE
Disable crossover, 14x performance improvement

### PR DESCRIPTION
**Pull request by staadecker**
This PR:

1. Disables Gurobi crossover since it was found to be unnecessary and negatively impacts performance. Results before and after the change were compared and little differences were found. This is a 14x performance improvement in total solve time!! **Dual values are however different when we include or don't include the crossover.**

2. Rounds numbers between `-1e-5` and `1e-5` to `0` in the output csv files.

3. Improves documentation on Gurobi methods.

4. Adds the flag `--recommended-robust` that re-enables crossover for Gurobi. This flag should be used if the barrier solve fails to produce an optimal solution.

### Additional notes

Here are some references showing that Gurobi crossover is unnecessary for our circustances:

- https://support.gurobi.com/hc/en-us/community/posts/360043330491-The-role-of-crossover-in-linear-programming
- https://stackoverflow.com/questions/38052754/drawbacks-of-avoiding-crossover-after-barrier-solve-in-linear-program
- https://scicomp.stackexchange.com/questions/772/what-are-the-advantages-disadvantages-of-interior-point-methods-over-simplex-met/780#780
- https://www.ibm.com/docs/en/icos/12.7.1.0?topic=optimizer-differences-between-barrier-simplex-optimizers
- https://www.ibm.com/docs/en/icos/12.7.1.0?topic=optimizer-barrier-simplex-crossover.

Note especially this quote from CPLEX documentation:

> You may choose to run the barrier optimizer without crossover. In such a case, the fact that barrier without crossover does not produce a basic solution has consequences. Without a basis, you will not be able to optimize the same or similar problems repeatedly using advanced start information. You will also not be able to obtain range information for performing sensitivity analysis.

### CODE REVIEW

**Comment by PatyHidalgo** [comment]
It’s fantastic to have run time reduced by so much!!! Great break trough! Can the default be to still include crossover and make it an option without? (Bullet 4) From the storage and curtailment results you showed me there were some small differences that make me wonder how this generalizes for any run. I think this approach is incredibly powerful to run many cases and identify key scenarios/findings and then only run the exact runs for the selected relevant subset that will be included in publications.
@jszinai if you get the chance to see the comparison Martin sent me on slack that’d be very helpful :) I think it’s a big decision and we’d benefit from other’s views :)
Great job!!!

**Comment by staadecker** [comment]
@PatyHidalgo @jszinai here are the latest updates (Paty already knows via slack). I've run with and without the change on 3 different scenarios. The `cost_components.csv` were exact matches to 5 significant digits with and without the change. As such my position is that although both solution may differ very slightly in results, they are both equally optimal since their objective function is the same. This would mean neither solution is more accurate and we should be using by default whichever one is faster. Curious to hear your thoughts!

**Comment by staadecker** [comment]
I am re-running one of the scenarios and will then post the outputs and comparison graphs so everyone can take a look at the differences.

**Comment by staadecker** [comment]
Ok results:

With crossover the total cost was:

1670419**12108.70**

Without crossover the total cost was:

1670419**83117.24**

The difference is that with the crossover the total cost was $71 000 dollars less. This is a 0.00004% difference in the total cost. Seems like such a difference is more than acceptable however if not I would recommend tightening the tolerance of the no crossover option to get more accurate results. Also attached are the comparison graphs between both cases.

**The dual plots are quite different!**

transmission_limit_duals
energy_balance_duals


buildout_per_period
costs
curtailment
curtailment_per_period
dispatch
emissions
emissions_duals
gen_buildout_per_tech_no_pred
generation_capacity_per_period
state_of_charge
storage_dispatch_cycle_duration
storage_dispatch_frequency
storage_duration
storage_duration_by_region
storage_duration_density
storage_duration_density_by_region
total_dispatch
transmission_capacity

**Comment by pesap** [comment]
I think we can merge this as it is. If there are some changes in the future we can do it in a separate PR.

**Pull request merged**
