### PR TITLE
Add warm starting option for linear programs

### PR DESCRIPTION
**Pull request by staadecker**
This PR adds the option to warm start a model for linear programs. Turns out the previous warm starting pull requests only did warm starting for MIPs.

### CODE REVIEW

**Comment by staadecker** [comment]
Log for my own future reference

```
Hydro
With warm start
10, 0.02
10, 0.00
10, 0.00
Without warm start
10, 0.00
10, 0.00
10, 0.00

3Zone-LP
Barrier

With warm start
19, 0.00
19, 0.00
19, 0.00
Without warm start
19, 0.02
19, 0.00
19, 0.00

3Zone-LP
Dual Simplex

with warm start (375 Dpushes, 12 PPushes)
355, 0.00, 375/12
357, 0.00, 355/14
355, 0.00, 355/12
without warm start
168, 0.00
168, 0.02
168, 0.00
```

**Comment by pesap** [comment]
Could you update me on this? So this will now work with our current model formulation?

**Comment by staadecker** [comment]
~~Yes! Once we merge this, runs will automatically generate a `results.pickle` file in outputs that can be used for warm starting. Warm starting works best when you ran the previous run *with* crossover (`--recommended` not `--recommended-fast`). To warm start from a previous run do `switch solve --recommended --warm-start <path_to_previous_run>`. I have yet to test how big the differences between both scenarios can be for warm starting to perform well.~~

**Comment by staadecker** [comment]
**Update**: This module works however the cases where we get performance benefits are limited. Warm starting is not enabled by default anymore but is still available via `--save-warm-start` and `--warm-start`. I've written documentation on what I've learnt regarding warm start.

To answer your question though, warm starting works and we should merge this one possible.

**Comment by pesap** [comment]
Ok. Thanks for the clarification. I am going to merge this.

**Pull request merged**
