### PR TITLE
Script to fix derating factor for transmission lines

### PR DESCRIPTION
**Pull request by pesap**
Paty,

I created the SQL script to fix the derating factor of the transmission lines. Since we do not have a transmission scenario, I just applied the fix to the transmission table. Do you think we need a transmission scenario table?

This could just be merge right away.

### CODE REVIEW

**Comment by PatyHidalgo** [comment]
Hi Pedro,
Thank you! But we should create a transmission_scenario_id, otherwise we won't be able to replicate previous runs/studies (we will lose replicability and this is very important to maintain for publications/good practice). Can you please add a new column to the transmission_lines tables (and also to the scenario tables), as well as editing get_inputs.py so it can pull the right data?
The existing rows in transmission_lines tables should be assigned transmission_scenario_id=1, then copy all these rows to create a set of rows for transmission_scenario_id=2. Only for these set or rows you'll set the derating factor to 0.95 instead.
UPDATE switch.transmission_lines SET derating_factor = 0.95 where transmission_scenario_id=2;

Thank you!

**Comment by PatyHidalgo** [comment]
Also, in the scenario table, all past scenarios should be assigned transmission_scenario_id=1 so it doesn't impact people's ongoing work.

**Comment by pesap** [comment]
Hi @PatyHidalgo ,

I think this new version should fix it. I included the new column transmission_scenario_id in both the database and the scripts that download the inputs. Also, I added scenario 179 that has the updated version of the transmission lines with the id `transmission_scenario_id = 2`.

I think this does not break the workflo from other people, but happy to fix it if it does!

**Comment by staadecker** [comment]
@pesap was the change from an 85 year lifespan to a 25 year lifespan intentional? If so do you mind explaining the reasoning behind the change. I'm not sure if this change went unnoticed by the others on your team @PatyHidalgo however if so it might have affected results. We should mark it in [the changelog](https://github.com/REAM-lab/switch/blob/wecc/REAM%20Model%20Changelog.md)

**Pull request merged**
